feat(reusable-nuget-package-build.yml): adding workflow for building …
CtheSigns/reusable-workflows-service pull request #27
Opened 2023-06-27 12:59 UTC by SerhiiVybach

…and pushing NuGet packages

2023-06-27 15:13 UTC, David-Pas approved these changes

2023-06-27 15:55 UTC, povisenko requested changes

2023-06-27 15:55 UTC, povisenko commented on .github/workflows/reusable-nuget-package-build.yml
> +        uses: actions/cache@v3
if you specifically only want to restore then use `uses: actions/cache/restore@v3`
see https://github.com/CtheSigns/reusable-workflows-service/blob/f6568da09db24e85b58ddadc157df72e5cc598cf/.github/workflows/reusable-ci-gradle.yml#L108

2023-06-27 15:55 UTC, povisenko commented on .github/workflows/reusable-nuget-package-build.yml
> +        uses: actions/cache@v3
you could also explicitly look to saving cache  via uses: actions/cache/save@v3

https://github.com/CtheSigns/reusable-workflows-service/blob/f6568da09db24e85b58ddadc157df72e5cc598cf/.github/workflows/reusable-ci-gradle.yml#L126C8-L126C36

2023-06-27 15:55 UTC, povisenko commented on .github/workflows/reusable-nuget-package-build.yml
> +        shell: bash
I'm sure you could also delete shell: bash and it work

2023-06-27 16:53 UTC, SerhiiVybach commented on .github/workflows/reusable-nuget-package-build.yml
> +        uses: actions/cache@v3
@povisenko, actually `actions/cache@v3` does the same but just saves implicitly as post actions, 
do you think using restore/save will be more convenient?

2023-06-27 17:12 UTC, SerhiiVybach commented on .github/workflows/reusable-nuget-package-build.yml
> +    name: "Build Nuget Package"
thanks, fixed in e681b61ae0591f1a59efb6857b62e6cb00540211

2023-06-27 17:12 UTC, SerhiiVybach commented on .github/workflows/reusable-nuget-package-build.yml
> +        shell: bash
thanks, fixed in e681b61ae0591f1a59efb6857b62e6cb00540211

2023-06-28 11:56 UTC, povisenko approved these changes

2023-06-28 11:56 UTC, povisenko commented on .github/workflows/reusable-nuget-package-build.yml
> +        uses: actions/cache@v3
makes sense
approved

2023-06-28 11:57 UTC, povisenko commented
@SerhiiVybach please do not forget to squash

2023-06-28 14:07 UTC, merged