feat([CTS-10271]): added customisation for java version
CtheSigns/reusable-workflows-service pull request #8
Opened 2022-11-07 15:08 UTC by vasyl-pryimak

2022-11-07 15:31 UTC, David-Pas approved these changes

2022-11-08 09:27 UTC, dmitry-kokora approved these changes

2022-11-18 14:24 UTC, povisenko requested changes

2022-11-18 14:24 UTC, povisenko commented on .github/workflows/reusable-cd.yml
> +          if [[ "$ENV" =~ ^(dev|dev-us|qa|uat|staging|prod|prod-us)$ ]]; then
I think that it's bad idea
extend the build with AWS region to deploy

2022-11-18 14:25 UTC, povisenko commented on .github/workflows/reusable-cd.yml
> +          if [[ "$ENV" =~ ^(dev|dev-us|qa|uat|staging|prod|prod-us)$ ]]; then
with the default one to the UK

2022-11-18 14:35 UTC, dmitry-kokora commented on .github/workflows/reusable-cd.yml
> +          if [[ "$ENV" =~ ^(dev|dev-us|qa|uat|staging|prod|prod-us)$ ]]; then
We discussed this possibility with @vasyl-pryimak , but we did not have time to implement it

2022-11-18 17:38 UTC, vasyl-pryimak commented on .github/workflows/reusable-cd.yml
> +          if [[ "$ENV" =~ ^(dev|dev-us|qa|uat|staging|prod|prod-us)$ ]]; then
added ecsClusterName customisation parameter

2022-11-21 07:33 UTC, povisenko approved these changes
looks good now
the only thing is that PR contains 2 features: custom java version and ECS cluster name would prefer it to be as a separate PR/commits next time

2022-11-21 07:33 UTC, povisenko commented
@vasyl-pryimak please squash as two commits and after that rebase onto main

2023-01-04 11:48 UTC, merged